
/*==============================================================*/
/* SCRIPT : TP CATALOGUES                                       */
/*==============================================================*/

--1)
CONNECT system/pwd ;
DROP USER USER1 CASCADE;
DROP USER USER2 CASCADE;

CREATE USER USER1 IDENTIFIED BY pwd;
CREATE USER USER2 IDENTIFIED BY pwd;
GRANT ALL PRIVILEGES to USER1;
GRANT CREATE SESSION , CREATE TABLE to USER2 ;

--2)
ALTER USER USER2 QUOTA UNLIMITED ON SYSTEM ;

CONNECT USER2/pwd;
CREATE TABLE ENTRETIEN_BATEAU (
	  NomAgent    VARCHAR2(40) ,
	  Nbat        NUMBER(3),
	  CONSTRAINT PK_NOMAGENT_NBAT PRIMARY KEY (NomAgent , Nbat)
);

--3)
CONNECT USER1/pwd ;
@C:\Users\Moflawer\Desktop\Dol_Gul_Dur\WorkShop_Tree\SQL\Almost_Done\SCRIPTs_Pour_TPs_BD2\Data_Base\Creation_Model_de_Donnees_Contraites.sql

--4)
GRANT SELECT , REFERENCES (nbat) ON BATEAU to USER2 ;

--5)
SELECT COUNT(*) FROM DICT ;
DESC DICT ;

--6)
SELECT * FROM DICT 
WHERE TABLE_NAME LIKE 'USER_TAB%' ;

--7)
SELECT COMMENTS AS A_quoi_sert_USER_TAB_PRIVS
FROM DICT 
WHERE TABLE_NAME = 'USER_TAB_PRIVS' ;

--8)
SELECT COMMENTS AS A_quoi_sert_ALL_TAB_COLUMNS
FROM DICT 
WHERE TABLE_NAME = 'ALL_TAB_COLUMNS' ;

SELECT COMMENTS AS A_quoi_sert_ALL_CONSTRAINTS
FROM DICT 
WHERE TABLE_NAME = 'ALL_CONSTRAINTS' ;

SELECT COMMENTS AS A_quoi_sert_USER_USERS
FROM DICT 
WHERE TABLE_NAME = 'USER_USERS' ;
 
--9)
SELECT COMMENTS AS DIFERENCE
FROM DICT 
WHERE TABLE_NAME = 'ALL_TABLES'
OR    TABLE_NAME = 'USER_TABLES';

--10)
DESC USER_USERS ;
SELECT  USERNAME AS NOM_UTILISATEUR , 
ACCOUNT_STATUS   AS ETAT_DU_COMPT,
DEFAULT_TABLESPACE AS TABLESPAC_PAR_DEFAULT 
FROM USER_USERS ;

--11)
DESC USER_TABLES ;
SELECT TABLE_NAME
FROM USER_TABLES ;

--12)
DESC ALL_TABLES ;
SELECT TABLE_NAME
FROM ALL_TABLES
WHERE OWNER = 'SYSTEM';

--13)
SELECT TABLE_NAME
FROM ALL_TABLES 
WHERE OWNER = 'USER2';

--14)
DESC ALL_TAB_COLUMNS;
SELECT COLUMN_NAME , DATA_TYPE , DATA_LENGTH , OWNER 
FROM ALL_TAB_COLUMNS 
WHERE TABLE_NAME = 'COMPETITION' ;

--15)
SELECT COLUMN_NAME , DATA_TYPE , DATA_LENGTH , OWNER 
FROM ALL_TAB_COLUMNS 
WHERE TABLE_NAME = 'ENTRETIEN_BATEAU' 
AND OWNER = 'USER2';

--16)
DESC ALL_CONSTRAINTS ;

ALTER TABLE USER2.ENTRETIEN_BATEAU
ADD CONSTRAINT FK_NBAT FOREIGN KEY (Nbat) REFERENCES BATEAU (nbat) ;

SELECT CONSTRAINT_NAME , CONSTRAINT_TYPE , TABLE_NAME , OWNER
FROM ALL_CONSTRAINTS
WHERE OWNER = 'USER2';

--17)
SELECT  CONSTRAINT_NAME ,CONSTRAINT_TYPE
FROM ALL_CONSTRAINTS
WHERE CONSTRAINT_TYPE = 'R'
AND   OWNER = 'USER1';

--18)
DESC ALL_TABLES ;
SELECT TABLE_NAME AS NOM_TABLE , OWNER AS PROPRIETAIRE 
FROM ALL_TABLES 
WHERE  TABLE_NAME = 'BATEAU';

--19)
-----------------------------------------------------a)
/*Catalogues USER_TAbLES , ALL_TAB_COLUMNS , ALL_CONSTRAINTS AVANT CREATION */

SELECT TABLE_NAME AS USER_TABLES_ANVANT
FROM   USER_TABLES ;

SELECT COLUMN_NAME , TABLE_NAME 
FROM ALL_TAB_COLUMNS
WHERE OWNER = 'USER1';

SELECT CONSTRAINT_NAME , CONSTRAINT_TYPE
FROM ALL_CONSTRAINTS
WHERE OWNER = 'USER1' ;

/*CREATION*/

CREATE TABLE SPONSOR (
             NomSponsor VARCHAR2(40) ,
			 Specialite VARCHAR2(40) ,
			 CONSTRAINT PK_NOMSPONSOR 
			 PRIMARY KEY (NomSponsor)
);

INSERT INTO SPONSOR VALUES ('CEVITAL' , 'alimentation') ;
INSERT INTO SPONSOR VALUES ('DJEZZY' ,'télécom') ;
INSERT INTO SPONSOR VALUES ('CONDOR' ,'éléctro-ménage') ;
INSERT INTO SPONSOR VALUES ('OOREDOO', 'télécom') ;
INSERT INTO SPONSOR VALUES ('STARLIGHT', 'éléctro-ménage') ;
INSERT INTO SPONSOR VALUES ('BNA' ,'banque') ;
INSERT INTO SPONSOR VALUES ('IRIS' ,'télécom') ;

/*Catalogues USER_TAbLES , ALL_TAB_COLUMNS , ALL_CONSTRAINTS APRES CREATION */

SELECT TABLE_NAME AS USER_TABLES_APRES
FROM   USER_TABLES ;

SELECT COLUMN_NAME , TABLE_NAME 
FROM ALL_TAB_COLUMNS
WHERE OWNER = 'USER1';

SELECT CONSTRAINT_NAME , CONSTRAINT_TYPE
FROM ALL_CONSTRAINTS
WHERE OWNER = 'USER1' ;

--------------------------------------------------b)
/*Catalogues ALL_CONSTRAINTS AVANT AJOUT de CONTRAINTE*/

SELECT CONSTRAINT_NAME , CONSTRAINT_TYPE
FROM ALL_CONSTRAINTS
WHERE OWNER = 'USER1' ;

/*AJOUT DE CONTRAINTE*/

ALTER TABLE BATEAU
ADD CONSTRAINT FK_SPONSOR_BATEAU_SPONSOR
FOREIGN KEY (sponsor)
REFERENCES SPONSOR (NomSponsor);

/*Catalogues ALL_CONSTRAINTS APRES AJOUT de CONTRAINTE*/

SELECT CONSTRAINT_NAME , CONSTRAINT_TYPE
FROM ALL_CONSTRAINTS
WHERE OWNER = 'USER1' ;

---------------------------------------------c)
/*Catalogue USER_TABLES ,ALL_TAB_COLUMNS ,ALL_CONSTRAINTS AVANT SUPPRESSION */

SELECT TABLE_NAME AS USER_TABLES_ANVANT
FROM   USER_TABLES ;

SELECT COLUMN_NAME , TABLE_NAME 
FROM ALL_TAB_COLUMNS
WHERE OWNER = 'USER1';

SELECT CONSTRAINT_NAME , CONSTRAINT_TYPE
FROM ALL_CONSTRAINTS
WHERE OWNER = 'USER1' ;

/*SUPPRESSION */ 
DROP TABLE PARTICIPANTS CASCADE CONSTRAINTS ;

/*Catalogue USER_TABLES ,ALL_TAB_COLUMNS ,ALL_CONSTRAINTS APRES SUPPRESSION */ 
 
SELECT TABLE_NAME AS USER_TABLES_APRES
FROM   USER_TABLES ;

SELECT COLUMN_NAME , TABLE_NAME 
FROM ALL_TAB_COLUMNS
WHERE OWNER = 'USER1';

SELECT CONSTRAINT_NAME , CONSTRAINT_TYPE
FROM ALL_CONSTRAINTS
WHERE OWNER = 'USER1' ;

----------------------------------------d)
/*Catalogue USER_TABLES , ALL_TAB_COLUMNS , USER_VIEWS AVANT CREATION de la VUE  */

SELECT VIEW_NAME AS USER_VIEWS_AVANT
FROM   USER_VIEWS ;

SELECT COLUMN_NAME , TABLE_NAME 
FROM ALL_TAB_COLUMNS
WHERE OWNER = 'USER1';

SELECT TABLE_NAME AS USER_TABLES_ANVANT
FROM   USER_TABLES ;

/* CREATION VUE*/

CREATE VIEW BATEAUX_GAGNANTS (Nom_Bateau ,Nom_Competition  , Date_Competition  , Prix) AS
(
SELECT u.nombat , p.Nomcomp , p.Datcomp , p.Prixcomp
FROM BATEAU u , COMPETITION p ,COURSES v
WHERE u.nbat = v.nbat 
AND   v.Ncomp = p.Ncomp
AND   v.Score = 1 
) ;

SELECT * FROM BATEAUX_GAGNANTS ;

 /*Catalogue USER_TABLES , ALL_TAB_COLUMNS ,USER_VIEWS APRES CREATION de la VUE  */

SELECT VIEW_NAME AS USER_VIEWS_APRES
FROM   USER_VIEWS ;

SELECT COLUMN_NAME , TABLE_NAME 
FROM ALL_TAB_COLUMNS
WHERE OWNER = 'USER1';

SELECT TABLE_NAME AS USER_TABLES_APRES
FROM   USER_TABLES ;
